language: php

php:
  - 7.0
  - 7.1

matrix:
  include:
    - php: 7.0
      env: coverage=no
    - php: 7.1
      env: coverage=yes

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [[ $coverage = 'yes' ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
